language: rust
script:
  - PROTOC_ZIP=protoc-3.7.1-linux-x86_64.zip
  - curl -OL https://github.com/google/protobuf/releases/download/v3.7.1/$PROTOC_ZIP
  - sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
  - rm -f $PROTOC_ZIP
  - cargo build --verbose --all
  - cargo test --verbose --all