matrix:
  include:
    # wangscript & napoca
    language: rust
    script:
      - cargo build --verbose --all
      - cargo test --verbose --all
    # napoca-client
    language: node_js
    node_js:
      - "stable"
    addons:
      apt:
        packages:
          - python3
    before_script:
      # Install protocol buffer compiler
      - PROTOC_ZIP=protoc-3.7.1-linux-x86_64.zip
      - curl -OL https://github.com/google/protobuf/releases/download/v3.7.1/$PROTOC_ZIP
      - sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
      - rm -f $PROTOC_ZIP
    script:
      - cd napoca-client
      - npm install
      - npm test
    # bettle
    language: node_js
    node_js:
      - "10.13"
    before_install:
      - npm i -g npm@6.4.1
    before_script:
      - npm config set strict-ssl false
      - npm install -g mocha
    script:
      - cd beetle
      - npm install
      - npm test
